version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "seve"
  - package-ecosystem: pip
    directory: "/python_dependencies/backend/"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    assignees:
      - "Bento007"
    groups:
      database:
        patterns:
          - "alembic"
          - "sqlalchemy"
          - "psycopg2"
      server:
        patterns:
          - "flask"
          - "gunicorn"
          - "setproctitle"
          - "connexion"

  - package-ecosystem: pip
    directory: "/python_dependencies/wmg/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "prathapsridharan"
  - package-ecosystem: pip
    directory: "/python_dependencies/upload_handler/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "ebezzi"
  - package-ecosystem: pip
    directory: "/python_dependencies/submissions/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "nayib-jose-gloria"
  - package-ecosystem: pip
    directory: "/python_dependencies/cellguide_pipeline/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "atarashansky"
  - package-ecosystem: pip
    directory: "/python_dependencies/processing/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "Bento007"
    groups:
      database:
        patterns:
          - "sqlalchemy*"
          - "psycopg2*"
      non-major-updates:
        patterns:
          - "*"
        applies-to: version-updates
        update-types:
          - patch
          - minor
        exclude-patterns:
          # The following packages do not have major versions. So a minor version updates may contain breaking changes.
          - "anndata"
          - "tiledb"
          - "numba"
          - "s3fs"
  - package-ecosystem: pip
    directory: "/python_dependencies/common/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "nayib-jose-gloria"
    groups:
      formatters:
        patterns:
          - "black"
          - "ruff"
      test-runners:
        patterns:
          - "pytest"
          - "coverage"
          - "allure"
  - package-ecosystem: npm
    directory: "/frontend/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "tihuan"
