name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 365
          days-before-issue-close: 14
          stale-issue-label: "stale"
          close-issue-label: "autoclosed"
          stale-issue-message: "This issue is stale because it has been open for 1 year with no activity. If no action is taken, it will be closed automatically 2 weeks from now."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale. Please re-open if you still need this to be addressed."
          days-before-pr-stale: 14
          days-before-pr-close: 3
          stale-pr-message: "This PR has not seen any activity in the past 2 weeks; if nobody comments or reviews it in the next 3 days, this PR will be closed."
          close-pr-message: "This PR was closed because it has been inactive for 17 days, 3 days since being marked as stale. Please re-open if you still need this to be addressed."
          stale-pr-label: "stale"
          close-pr-label: "autoclosed"
          exempt-draft-pr: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
