name: Zenhub Close Issue Ready for Prod

on:
  push:
    branches:
      - prod

jobs:
  # run the python script to close the issue in zenhub
  close-issue:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Close Issue
        run: |
          pip install requests
          python3 ./scripts/zenhub_close.py >> $GITHUB_STEP_SUMMARY
        env:
          ZENHUB_TOKEN: ${{ secrets.ZENHUB_TOKEN }}
